### ISSUE TITLE
rule 可能不存在test字段

### ISSUE THREAD

**Issue by abigmiu** [styzhang/css-unicode-loader#1]
我在使用的时候， vue-cli项目， 发现`config.module.rules`里面有一项内容不存在`test`字段， 所以可以先判断有没有`test字段` （为了加粗显示， 就没有使用代码块了， 直接用的文本）

// vue.config.js
module.exports = {
  configureWebpack: config => {
    const sassLoader = require.resolve('sass-loader');
    config.module.rules.filter(rule => {
      return ` **rule.test**` && rule.test.toString().indexOf("scss") !== -1;
    })
      .forEach(rule => {
        rule.oneOf.forEach(oneOfRule => {
          const sassLoaderIndex = oneOfRule.use.findIndex(item => item.loader === sassLoader);
          oneOfRule.use.splice(sassLoaderIndex, 0,
          	{ loader: require.resolve("css-unicode-loader") });
        });
      });
    }
}

**Comment by styzhang** [comment]
嗯，明白你的意思，谢谢你的建议；不过用法中说明中给出的是个配置demo，并不适用所有场景。
- 可能项目中加入一些rule不是使用`test`去匹配
- 也有可能使用的是`sass file` 而不是`scss file`：
`config.module.rules.filter(rule => {
   return rule.test.toString().indexOf('**sass**') !== -1;
})
.forEach(rule => {
   ...
});`
- 也可能因为使用vue-cli的版本有所差异
...
对于这些不确定的情况可以先使用 `vue inspect > webpack-config-out.js` 来查看下当前项目的配置，然后配置的时候让`css-unicode-loader`在`use`中的位置是在`sass-loader`之前就行

**Comment by styzhang** [comment]
> 我在使用的时候， vue-cli项目， 发现`config.module.rules`里面有一项内容不存在`test`字段， 所以可以先判断有没有`test字段` （为了加粗显示， 就没有使用代码块了， 直接用的文本）
> 
> // vue.config.js module.exports = { configureWebpack: config => { const sassLoader = require.resolve('sass-loader'); config.module.rules.filter(rule => { return ` **rule.test**` && rule.test.toString().indexOf("scss") !== -1; }) .forEach(rule => { rule.oneOf.forEach(oneOfRule => { const sassLoaderIndex = oneOfRule.use.findIndex(item => item.loader === sassLoader); oneOfRule.use.splice(sassLoaderIndex, 0, { loader: require.resolve("css-unicode-loader") }); }); }); } }

@abigmiu 嗯，明白你的意思，谢谢你的建议；不过用法中说明中给出的是个配置demo，并不适用所有场景。
- 可能项目中加入一些rule不是使用`test`去匹配
- 也有可能使用的是`sass file` 而不是`scss file`：
`config.module.rules.filter(rule => {
   return rule.test.toString().indexOf(**'sass'**) !== -1;
})
.forEach(rule => {
   ...
});`
- 也可能因为使用vue-cli的版本有所差异
...
对于这些不确定的情况可以先使用 `vue inspect > webpack-config-out.js` 来查看下当前项目的配置，然后配置的时候让`css-unicode-loader`在`use`中的位置是在`sass-loader`之前就行
