### ISSUE TITLE
有没有大佬教一下 vue-cli 4.x 怎么写配置

### ISSUE THREAD

**Issue by DoveAz** [styzhang/css-unicode-loader#3]

**Comment by styzhang** [comment]
![image](https://user-images.githubusercontent.com/44157286/164424736-249b2a16-7a7b-46b5-857b-1d325b0e0989.png)

**Comment by styzhang** [comment]
MD里有个demo示例：
![image](https://user-images.githubusercontent.com/44157286/164425101-03e1eca1-2086-4dab-a439-12109a572b93.png)
按这个不行的话，先使用`vue inspect > output.js`输出查看下webpack的配置，找到`sass-loader`的相关配置，然后配置将`css-unicode-loader`配置`sass-loader`前面就行了，例如：
未配置`css-unicode-loader`前的输出：
![image](https://user-images.githubusercontent.com/44157286/164427249-30b38647-4c5c-4d62-b436-cb164360c384.png)
配置`css-unicode-loader`后的输出：
![image](https://user-images.githubusercontent.com/44157286/164428513-fb17462a-58da-4a22-8d53-cb135b063d68.png)

**Comment by styzhang** [comment]
@DoveAz 
MD里有个用法示例：
![image](https://user-images.githubusercontent.com/44157286/164425101-03e1eca1-2086-4dab-a439-12109a572b93.png)
按这个不行的话，先使用`vue inspect > output.js`输出查看下webpack的配置，找到`sass-loader`的相关配置，然后配置将`css-unicode-loader`配置`sass-loader`前面就行了，例如：
未配置`css-unicode-loader`前的输出：
![image](https://user-images.githubusercontent.com/44157286/164427249-30b38647-4c5c-4d62-b436-cb164360c384.png)
配置`css-unicode-loader`后的输出：
![image](https://user-images.githubusercontent.com/44157286/164428513-fb17462a-58da-4a22-8d53-cb135b063d68.png)

**Comment by styzhang** [comment]
> > @DoveAz
> > MD里有个用法示例：
> > ![image](https://user-images.githubusercontent.com/44157286/164425101-03e1eca1-2086-4dab-a439-12109a572b93.png)
> > 按这个不行的话，先使用`vue inspect > output.js`输出查看下webpack的配置，找到`sass-loader`的相关配置，然后配置将`css-unicode-loader`配置`sass-loader`前面就行了，例如：
> > 未配置`css-unicode-loader`前的输出：
> > ![image](https://user-images.githubusercontent.com/44157286/164427249-30b38647-4c5c-4d62-b436-cb164360c384.png)
> > 配置`css-unicode-loader`后的输出：
> > ![image](https://user-images.githubusercontent.com/44157286/164428513-fb17462a-58da-4a22-8d53-cb135b063d68.png)

**Comment by DoveAz** [comment]
多谢大佬，原来是我看走眼了，写在chainWebpack里了，一直报错
