### ISSUE TITLE
你好，想问一下乱码问题的原因是sass-loader的问题吗？感谢！

### ISSUE THREAD

**Issue by sjzgit** [styzhang/css-unicode-loader#4]
环境：node16 + @vue/cli4 + elementUI2.15.7 + sass 1.43.4 + sass-loader 10.1.1
该环境中打包之后会出现 el-icon css乱码：
![image](https://user-images.githubusercontent.com/26371424/164586420-7c6c196c-fec2-4c1f-a4e5-7e831754410f.png)

但是同样的版本使用vitejs构建的项目就正常，当然vitejs不需要手动引入：sass-loader。

使用了大佬的这个loader确实解决了，想了解一下深层原因，请教一下

**Comment by styzhang** [comment]
@sjzgit 和sass-loader没关系，是sass（dart-sass）的原因，可参考这个issue下这个comment：[#3526-764542268](https://github.com/PanJiaChen/vue-element-admin/issues/3526#issuecomment-764542268)
不过这个问题已经在[dart-sass v1.38.0](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1380)的版本修复了，**不过只在扩展模式(expanded)下有效，压缩模式(compressed)下依然还有这个问题**，一般项目中都是压缩模式。
下面是我本地单独用sass命令编译element的图标样式的结果
扩展模式下dart-sass v1.37.0版本与dart-sass v1.38.0版本的对比：
![image](https://user-images.githubusercontent.com/44157286/167300021-5e4ce1c4-14ed-430b-81cb-cf6c5f283950.png)

可以看到1.37.0版本编译输出的是Unicode明文（编辑器上看着是空格，但其实是乱码，粘贴到浏览器上显示就变成了乱码），而1.38.0版本输出的Unicode编码
压缩模式下dart-sass v1.37.0版本与dart-sass v1.38.0版本的对比：
![image](https://user-images.githubusercontent.com/44157286/167300925-3bf4f0fa-e47b-4ef2-be36-f53a7df2a723.png)
**可以看到压缩模式下的编译结果还是unicode明文，也就是乱码了**
你自己可以本地单独用sass命令编程输出css文件试试

**Comment by jetBn** [comment]
sass升级到1.38.0使用那个element不是有warning 怎么去除。

**Comment by styzhang** [comment]
> sass升级到1.38.0使用那个element不是有warning 怎么去除。
@jetBn sass 命令编译的时候带上`--quiet`参数就可以了
![image](https://user-images.githubusercontent.com/44157286/167304757-02ca98cf-140b-45e7-b6ea-7014bda47d03.png)

![image](https://user-images.githubusercontent.com/44157286/167304794-ef2dee4e-4ee5-4eb6-881d-a9e3c5a23a06.png)

这个warning不影响输出，去不去除都没关系；另外注意即使升到1.38.0+版本压缩模式下编译输出还是乱码

**Comment by jetBn** [comment]
那还是用这个插件 吧感觉 @styzhang

**Comment by sjzgit** [comment]
> 

好的，非常感谢

**Comment by zuoyifeng** [comment]
> 

这个忽略的写法具体怎么弄

**Comment by zuoyifeng** [comment]
意思这个警告不影响实际除法功能吗？

**Comment by zuoyifeng** [comment]
> > sass升级到1.38.0使用那个element不是有warning 怎么去除。
> > @jetBn sass 命令编译的时候带上`--quiet`参数就可以了
> > ![image](https://user-images.githubusercontent.com/44157286/167304757-02ca98cf-140b-45e7-b6ea-7014bda47d03.png)
> 
> ![image](https://user-images.githubusercontent.com/44157286/167304794-ef2dee4e-4ee5-4eb6-881d-a9e3c5a23a06.png)
> 
> 这个warning不影响输出，去不去除都没关系；另外注意即使升到1.38.0+版本压缩模式下编译输出还是乱码

请教一下，这个忽略的写法具体怎么敲得，按这种改法，意思这个警告不影响实际除法功能吗？不用理会？
